jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: true
      - run:
          command: |
            pytest --version
          name: Test
      - run:
          command: |
            black . --check
          name: Lint
orbs:
  python: circleci/python@1.4.0
version: 2.1
workflows:
  main:
    jobs:
      - build
