version: 2.1

jobs:
  "python-3.7":
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run:
          name: Create virtualenv
          command: |
            python -m venv venv

      - run:
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install .[dev]

      - run:
          name: Run tests
          command: |
            python -m pytest

      - run:
          name: Verify black
          command: |
            black . --check

workflows:
  version: 2
  build:
    jobs:
      - "python-3.7"
