version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.5

    steps:
      - checkout

      - run:
          name: Create virtualenv
          command: |
            python -m venv venv

      - run:
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install .[dev]

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: Verify black
          command: |
            . venv/bin/activate
            black . --check

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
