jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: "requirements-dev.txt"
          pkg-manager: pip
      - run:
          command: |
            pytest
          name: Run Test
      - run:
          command: |
            black . --check
          name: Check Lint
orbs:
  python: circleci/python@1.4.0
version: 2.1
workflows:
  main:
    jobs:
      - build
